on: [push, workflow_dispatch]

env:
  TOOLS_URL: https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1
  QT_VER: qt5156
  TARGETS: "x11-static rpi1-static rpi2-static rpi3-static rpi4-static"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: APT deps
        run: sudo apt-get update && sudo apt-get install -y
          g++
          libasound-dev
          libgl1-mesa-dev
          libgstreamer-plugins-base1.0-dev
          libpulse-dev
          libudev-dev
          libxcb-glx0-dev
          libxcb-icccm4-dev
          libxcb-image0-dev
          libxcb-keysyms1-dev
          libxcb-randr0-dev
          libxcb-render-util0-dev
          libxcb-shape0-dev
          libxcb-sync-dev
          libxcb-util-dev
          libxcb-xfixes0-dev
          libxcb-xinerama0-dev
          libxi-dev
          libxkbcommon-dev
          libxkbcommon-x11-dev
          libzstd-dev
          ninja-build
          xvfb
      - name: Get Qt
        working-directory: /tmp
        run: |
          for target in ${TARGETS}; do wget ${TOOLS_URL}/${QT_VER}_${target}.tar.xz; done
          wget ${TOOLS_URL}/rpi-sysroot_buster_brcm.tar.xz
          wget ${TOOLS_URL}/rpi-sysroot_buster_mesa.tar.xz
          for f in *.tar.xz; do sudo tar xJf ${f} -C /opt/; done
          sudo ln -s ${QT_VER}_x11-static /opt/${QT_VER}_x11-static_hosttools
      - uses: actions/checkout@v2
      - name: Build
        run: for target in ${TARGETS}; do
          mkdir build_${target} && cd build_${target} &&
          /opt/${QT_VER}_${target}_hosttools/bin/qmake .. &&
          make install INSTALL_ROOT=$PWD/../install_${target} &&
          cd ..;
          done &&
          mkdir dist
      - name: Package
        working-directory: ./dist
        run: for target in ${TARGETS}; do
          zip -j retropie-frontendchooser_${target}.zip
            ../install_${target}/opt/retropie-frontendchooser/bin/retropie-frontendchooser;
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/*.zip
